#Discussor
CONTEXT_MAX_LENGTH = 50

#Tag
SECONDARY_TAG_MAX_LENGTH = 100
TERTIARY_TAG_MAX_LENGTH = 100

#Follow
FOLLOW_CATEGORY_MAX_LENGTH = 11

#DISCUSSION
DISCUSSION_TITLE_MIN_LENGTH = 25
DISCUSSION_CONTENT_MIN_LENGTH = 100